name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: aelozen
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Commit and push the generated animation
      - name: Commit and push
        run: |
          git config --global user.name 'aelozen'
          git config --global user.email 'alexgross95@gmail.com'
          git checkout -b update-animation
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation [skip ci]"
          git push -u origin update-animation

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the correct secret name here

      # Create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update snake animation [skip ci]"
          title: "Update Snake Animation"
          body: "Automatically updated the snake animation."
          branch: update-animation
